## 1. Views and Copies

In [1]:
import numpy as np

In [2]:
mi_casa = np.array([-45, -31, -12, 0, 2, 25, 51, 99])

In [3]:
su_casa = mi_casa

###### Reference equality:

In [4]:
mi_casa is su_casa

True

In [5]:
id(mi_casa)

1659126540288

In [6]:
id(su_casa)

1659126540288

###### Value equality:

In [7]:
mi_casa == su_casa

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [8]:
su_casa[2] = 555

In [9]:
su_casa

array([-45, -31, 555,   0,   2,  25,  51,  99])

In [10]:
mi_casa

array([-45, -31, 555,   0,   2,  25,  51,  99])

In [11]:
tree_casa = np.array([-45, -31, 555, 0, 2, 25, 51, 99])

In [12]:
mi_casa == tree_casa

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [13]:
mi_casa is tree_casa

False

In [14]:
id(mi_casa)

1659126540288

In [15]:
id(su_casa)

1659126540288

In [17]:
id(tree_casa)

1659145315552

In [18]:
mi_casa

array([-45, -31, 555,   0,   2,  25,  51,  99])

In [19]:
su_casa

array([-45, -31, 555,   0,   2,  25,  51,  99])

In [20]:
tree_casa

array([-45, -31, 555,   0,   2,  25,  51,  99])

#### View: a shallow copy

In [21]:
farm_house = mi_casa.view()

In [22]:
farm_house

array([-45, -31, 555,   0,   2,  25,  51,  99])

In [24]:
farm_house.shape = (2, 4)
farm_house

array([[-45, -31, 555,   0],
       [  2,  25,  51,  99]])

In [25]:
mi_casa

array([-45, -31, 555,   0,   2,  25,  51,  99])

#### Deep Copy

In [27]:
dog_house = np.copy(mi_casa)

In [28]:
dog_house

array([-45, -31, 555,   0,   2,  25,  51,  99])

In [29]:
mi_casa

array([-45, -31, 555,   0,   2,  25,  51,  99])

In [30]:
dog_house is mi_casa

False

In [31]:
dog_house[1] = 999

In [32]:
dog_house

array([-45, 999, 555,   0,   2,  25,  51,  99])

In [33]:
mi_casa

array([-45, -31, 555,   0,   2,  25,  51,  99])

## 2. Array Attributes

- Number of dimensions
- shape
- size (number of elements)
- data type for elements
- item size for each element within an array
- type (for the array; not for elements within array)

In [34]:
a = np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [35]:
a.ndim

3

In [36]:
a.shape

(2, 3, 4)

In [37]:
a.size

24

In [38]:
a.dtype

dtype('int32')

In [39]:
a.itemsize

4

In [40]:
type(a)

numpy.ndarray

## 3. Adding and Removing Elements from NumPy Arrays

- append
- horizontal stacking
- vertical stacking
- insert
- delete

In [42]:
a = np.array(np.arange(24)).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

#### 3.1 Append

In [43]:
b=np.append(a, [5,6,7,8])
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  5,  6,  7,  8])

In [44]:
b.shape

(28,)

In [45]:
b.reshape((7, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 5,  6,  7,  8]])

In [46]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [47]:
c = np.array(np.arange(24)).reshape(2,3,4) * 10 + 3
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [48]:
np.append(a, c, axis = 0)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [49]:
np.append(a, c, axis=0).shape

(4, 3, 4)

In [50]:
np.append(a, c, axis=1)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [51]:
np.append(a, c, axis=2)

array([[[  0,   1,   2,   3,   3,  13,  23,  33],
        [  4,   5,   6,   7,  43,  53,  63,  73],
        [  8,   9,  10,  11,  83,  93, 103, 113]],

       [[ 12,  13,  14,  15, 123, 133, 143, 153],
        [ 16,  17,  18,  19, 163, 173, 183, 193],
        [ 20,  21,  22,  23, 203, 213, 223, 233]]])

#### 3.2 Horizontal Stasking

In [52]:
my_hay_stack = np.hstack((a,c))
my_hay_stack

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [53]:
my_hay_stack[0,0,2] = 999
my_hay_stack

array([[[  0,   1, 999,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [54]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [55]:
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

__Stacking creates copies not views__

#### 3.3 Inserting

In [56]:
after_insert_array = np.insert (c, 1, 444, axis=0)
after_insert_array

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[444, 444, 444, 444],
        [444, 444, 444, 444],
        [444, 444, 444, 444]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [57]:
np.insert(c, 1, 444, axis=1)

array([[[  3,  13,  23,  33],
        [444, 444, 444, 444],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [444, 444, 444, 444],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [58]:
np.insert(c, 1, 444, axis=2)

array([[[  3, 444,  13,  23,  33],
        [ 43, 444,  53,  63,  73],
        [ 83, 444,  93, 103, 113]],

       [[123, 444, 133, 143, 153],
        [163, 444, 173, 183, 193],
        [203, 444, 213, 223, 233]]])

#### 3.4 Deleting

In [59]:
d = np.empty(c.shape)
np.copyto(d, c)
d

array([[[  3.,  13.,  23.,  33.],
        [ 43.,  53.,  63.,  73.],
        [ 83.,  93., 103., 113.]],

       [[123., 133., 143., 153.],
        [163., 173., 183., 193.],
        [203., 213., 223., 233.]]])

In [60]:
np.delete(d, 1, axis=0)

array([[[  3.,  13.,  23.,  33.],
        [ 43.,  53.,  63.,  73.],
        [ 83.,  93., 103., 113.]]])

In [61]:
np.delete(d, 1, axis=1)

array([[[  3.,  13.,  23.,  33.],
        [ 83.,  93., 103., 113.]],

       [[123., 133., 143., 153.],
        [203., 213., 223., 233.]]])

In [62]:
np.delete(d, 1, axis=2)

array([[[  3.,  23.,  33.],
        [ 43.,  63.,  73.],
        [ 83., 103., 113.]],

       [[123., 143., 153.],
        [163., 183., 193.],
        [203., 223., 233.]]])

## 4. Joining and Splitting Arrays

- concatenate
- stack
- split

#### 4.1 concatenate
documentation: http://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html

In [70]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
a

array([[1, 2],
       [3, 4]])

In [71]:
together = np.concatenate((a, b), axis=0)
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [72]:
together[1, 1] = 555
together

array([[  1,   2],
       [  3, 555],
       [  5,   6]])

In [73]:
a

array([[1, 2],
       [3, 4]])

In [75]:
b

array([[5, 6]])

In [76]:
c = np.array([[1, 2], [3, 4]]) *3 + 5
c

array([[ 8, 11],
       [14, 17]])

In [77]:
np.concatenate((a, c), axis=1)

array([[ 1,  2,  8, 11],
       [ 3,  4, 14, 17]])

#### 4.2 stack

In [78]:
arrays = np.zeros((5,3,4))
for n in range(5):
    arrays[n] = np.random.randn(3, 4)
    
arrays

array([[[ 0.71189257, -0.93003126,  1.0093114 ,  0.71227594],
        [ 0.68343257, -0.34529269,  0.96127691, -0.74033569],
        [-1.44326553, -0.19680861, -0.1261543 ,  0.32964908]],

       [[ 0.58457958, -0.29475961, -0.31988138,  0.71738998],
        [-1.56025858, -1.4077787 , -0.65618515,  0.9556146 ],
        [-0.96328004,  0.45408769, -0.60270524,  0.07315767]],

       [[-0.75860752, -1.24973076,  0.30377602,  0.17696616],
        [ 0.77684405,  0.53574336, -0.84329956, -1.65137811],
        [ 0.01584603,  0.83608168,  0.27193639,  1.06926173]],

       [[-1.60767833,  0.23884882,  0.49089556, -0.68152321],
        [-0.46788096, -0.16107717, -0.96432213,  0.29080654],
        [ 0.68673241, -2.78678684,  0.3595588 , -0.84614011]],

       [[ 0.25117511,  0.3723027 , -0.17599708, -0.68081485],
        [-1.08583484, -1.01550555,  1.01777549,  0.78517846],
        [-1.51065424, -0.59557619, -0.89649621,  0.92697151]]])

In [79]:
stack0 = np.stack(arrays, axis=0)
stack1 = np.stack(arrays, axis=1)
stack2 = np.stack(arrays, axis=2)

In [80]:
my_stacks = np.array([stack0.shape, stack1.shape, stack2.shape])
my_stacks

array([[5, 3, 4],
       [3, 5, 4],
       [3, 4, 5]])

In [81]:
stack0

array([[[ 0.71189257, -0.93003126,  1.0093114 ,  0.71227594],
        [ 0.68343257, -0.34529269,  0.96127691, -0.74033569],
        [-1.44326553, -0.19680861, -0.1261543 ,  0.32964908]],

       [[ 0.58457958, -0.29475961, -0.31988138,  0.71738998],
        [-1.56025858, -1.4077787 , -0.65618515,  0.9556146 ],
        [-0.96328004,  0.45408769, -0.60270524,  0.07315767]],

       [[-0.75860752, -1.24973076,  0.30377602,  0.17696616],
        [ 0.77684405,  0.53574336, -0.84329956, -1.65137811],
        [ 0.01584603,  0.83608168,  0.27193639,  1.06926173]],

       [[-1.60767833,  0.23884882,  0.49089556, -0.68152321],
        [-0.46788096, -0.16107717, -0.96432213,  0.29080654],
        [ 0.68673241, -2.78678684,  0.3595588 , -0.84614011]],

       [[ 0.25117511,  0.3723027 , -0.17599708, -0.68081485],
        [-1.08583484, -1.01550555,  1.01777549,  0.78517846],
        [-1.51065424, -0.59557619, -0.89649621,  0.92697151]]])

In [82]:
stack1

array([[[ 0.71189257, -0.93003126,  1.0093114 ,  0.71227594],
        [ 0.58457958, -0.29475961, -0.31988138,  0.71738998],
        [-0.75860752, -1.24973076,  0.30377602,  0.17696616],
        [-1.60767833,  0.23884882,  0.49089556, -0.68152321],
        [ 0.25117511,  0.3723027 , -0.17599708, -0.68081485]],

       [[ 0.68343257, -0.34529269,  0.96127691, -0.74033569],
        [-1.56025858, -1.4077787 , -0.65618515,  0.9556146 ],
        [ 0.77684405,  0.53574336, -0.84329956, -1.65137811],
        [-0.46788096, -0.16107717, -0.96432213,  0.29080654],
        [-1.08583484, -1.01550555,  1.01777549,  0.78517846]],

       [[-1.44326553, -0.19680861, -0.1261543 ,  0.32964908],
        [-0.96328004,  0.45408769, -0.60270524,  0.07315767],
        [ 0.01584603,  0.83608168,  0.27193639,  1.06926173],
        [ 0.68673241, -2.78678684,  0.3595588 , -0.84614011],
        [-1.51065424, -0.59557619, -0.89649621,  0.92697151]]])

In [83]:
stack2

array([[[ 0.71189257,  0.58457958, -0.75860752, -1.60767833,
          0.25117511],
        [-0.93003126, -0.29475961, -1.24973076,  0.23884882,
          0.3723027 ],
        [ 1.0093114 , -0.31988138,  0.30377602,  0.49089556,
         -0.17599708],
        [ 0.71227594,  0.71738998,  0.17696616, -0.68152321,
         -0.68081485]],

       [[ 0.68343257, -1.56025858,  0.77684405, -0.46788096,
         -1.08583484],
        [-0.34529269, -1.4077787 ,  0.53574336, -0.16107717,
         -1.01550555],
        [ 0.96127691, -0.65618515, -0.84329956, -0.96432213,
          1.01777549],
        [-0.74033569,  0.9556146 , -1.65137811,  0.29080654,
          0.78517846]],

       [[-1.44326553, -0.96328004,  0.01584603,  0.68673241,
         -1.51065424],
        [-0.19680861,  0.45408769,  0.83608168, -2.78678684,
         -0.59557619],
        [-0.1261543 , -0.60270524,  0.27193639,  0.3595588 ,
         -0.89649621],
        [ 0.32964908,  0.07315767,  1.06926173, -0.84614011,
          0

#### 4.3 Split

for information: http://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html

In [84]:
temp = np.arange(5)
np.split(temp,1)

[array([0, 1, 2, 3, 4])]

In [85]:
before_split = stack0
before_split.shape

(5, 3, 4)

In [86]:
s0=np.split (before_split, 5, axis=0)
s0

[array([[[ 0.71189257, -0.93003126,  1.0093114 ,  0.71227594],
         [ 0.68343257, -0.34529269,  0.96127691, -0.74033569],
         [-1.44326553, -0.19680861, -0.1261543 ,  0.32964908]]]),
 array([[[ 0.58457958, -0.29475961, -0.31988138,  0.71738998],
         [-1.56025858, -1.4077787 , -0.65618515,  0.9556146 ],
         [-0.96328004,  0.45408769, -0.60270524,  0.07315767]]]),
 array([[[-0.75860752, -1.24973076,  0.30377602,  0.17696616],
         [ 0.77684405,  0.53574336, -0.84329956, -1.65137811],
         [ 0.01584603,  0.83608168,  0.27193639,  1.06926173]]]),
 array([[[-1.60767833,  0.23884882,  0.49089556, -0.68152321],
         [-0.46788096, -0.16107717, -0.96432213,  0.29080654],
         [ 0.68673241, -2.78678684,  0.3595588 , -0.84614011]]]),
 array([[[ 0.25117511,  0.3723027 , -0.17599708, -0.68081485],
         [-1.08583484, -1.01550555,  1.01777549,  0.78517846],
         [-1.51065424, -0.59557619, -0.89649621,  0.92697151]]])]

In [87]:
type(s0)

list

In [88]:
s0[1]

array([[[ 0.58457958, -0.29475961, -0.31988138,  0.71738998],
        [-1.56025858, -1.4077787 , -0.65618515,  0.9556146 ],
        [-0.96328004,  0.45408769, -0.60270524,  0.07315767]]])

In [89]:
type(s0[1])

numpy.ndarray

In [90]:
s0[1].shape

(1, 3, 4)

In [91]:
s1=np.split (before_split, 3, axis=1)
s1

[array([[[ 0.71189257, -0.93003126,  1.0093114 ,  0.71227594]],
 
        [[ 0.58457958, -0.29475961, -0.31988138,  0.71738998]],
 
        [[-0.75860752, -1.24973076,  0.30377602,  0.17696616]],
 
        [[-1.60767833,  0.23884882,  0.49089556, -0.68152321]],
 
        [[ 0.25117511,  0.3723027 , -0.17599708, -0.68081485]]]),
 array([[[ 0.68343257, -0.34529269,  0.96127691, -0.74033569]],
 
        [[-1.56025858, -1.4077787 , -0.65618515,  0.9556146 ]],
 
        [[ 0.77684405,  0.53574336, -0.84329956, -1.65137811]],
 
        [[-0.46788096, -0.16107717, -0.96432213,  0.29080654]],
 
        [[-1.08583484, -1.01550555,  1.01777549,  0.78517846]]]),
 array([[[-1.44326553, -0.19680861, -0.1261543 ,  0.32964908]],
 
        [[-0.96328004,  0.45408769, -0.60270524,  0.07315767]],
 
        [[ 0.01584603,  0.83608168,  0.27193639,  1.06926173]],
 
        [[ 0.68673241, -2.78678684,  0.3595588 , -0.84614011]],
 
        [[-1.51065424, -0.59557619, -0.89649621,  0.92697151]]])]

In [92]:
s2=np.split (before_split, 4, axis=2)
s2

[array([[[ 0.71189257],
         [ 0.68343257],
         [-1.44326553]],
 
        [[ 0.58457958],
         [-1.56025858],
         [-0.96328004]],
 
        [[-0.75860752],
         [ 0.77684405],
         [ 0.01584603]],
 
        [[-1.60767833],
         [-0.46788096],
         [ 0.68673241]],
 
        [[ 0.25117511],
         [-1.08583484],
         [-1.51065424]]]),
 array([[[-0.93003126],
         [-0.34529269],
         [-0.19680861]],
 
        [[-0.29475961],
         [-1.4077787 ],
         [ 0.45408769]],
 
        [[-1.24973076],
         [ 0.53574336],
         [ 0.83608168]],
 
        [[ 0.23884882],
         [-0.16107717],
         [-2.78678684]],
 
        [[ 0.3723027 ],
         [-1.01550555],
         [-0.59557619]]]),
 array([[[ 1.0093114 ],
         [ 0.96127691],
         [-0.1261543 ]],
 
        [[-0.31988138],
         [-0.65618515],
         [-0.60270524]],
 
        [[ 0.30377602],
         [-0.84329956],
         [ 0.27193639]],
 
        [[ 0.49089556],
 

## 5. Array Shape Manipulation

#### 5.1 Reshape
from: http://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html#numpy.reshape

NOTE: This will be a new view object if possible; otherwise, it will be a copy.

In [93]:
my_start_array = np.array(np.arange(24))
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [94]:
my_start_array.shape

(24,)

In [95]:
my_3_8_array = my_start_array.reshape((3,8))
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [96]:
my_3_8_array[0,0] = 1234
my_3_8_array

array([[1234,    1,    2,    3,    4,    5,    6,    7],
       [   8,    9,   10,   11,   12,   13,   14,   15],
       [  16,   17,   18,   19,   20,   21,   22,   23]])

In [97]:
my_start_array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

__my_3_8_array is a view of my_star_array__

#### 5.3 ravel()

In [98]:
my_ravel_array = my_3_8_array.ravel()
my_ravel_array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

__Returns a continuous flatten array__

#### 5.4 flat()

In [99]:
for n in my_3_8_array.flat:
    print(n)

1234
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


__Returns an interator__

## 6. Rearranging Array Elements

#### fliplr "flip left right"
from: http://docs.scipy.org/doc/numpy/reference/generated/numpy.fliplr.html#numpy.fliplr

Flip array in the left/right direction.

In [100]:
my_start_array = np.array(np.arange(24))
my_3_8_array = my_start_array.reshape((3,8))
my_2_3_4_array = my_3_8_array.reshape((2,3,4))

In [101]:
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [102]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [103]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [104]:
np.fliplr(my_3_8_array)

array([[ 7,  6,  5,  4,  3,  2,  1,  0],
       [15, 14, 13, 12, 11, 10,  9,  8],
       [23, 22, 21, 20, 19, 18, 17, 16]])

In [105]:
np.fliplr(my_2_3_4_array)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

#### flipud "flip up down"

In [106]:
np.flipud(my_3_8_array)

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7]])

In [107]:
np.flipud(my_2_3_4_array)

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

#### roll()

In [108]:
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [109]:
np.roll(my_start_array, 5)

array([19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 16, 17, 18])

In [110]:
np.roll(my_start_array, -5)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23,  0,  1,  2,  3,  4])

In [111]:
np.roll(my_2_3_4_array, 2)

array([[[22, 23,  0,  1],
        [ 2,  3,  4,  5],
        [ 6,  7,  8,  9]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]]])

In [112]:
np.roll(my_2_3_4_array, -2)

array([[[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]],

       [[14, 15, 16, 17],
        [18, 19, 20, 21],
        [22, 23,  0,  1]]])

#### rot90()

In [113]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [114]:
np.rot90(my_3_8_array)

array([[ 7, 15, 23],
       [ 6, 14, 22],
       [ 5, 13, 21],
       [ 4, 12, 20],
       [ 3, 11, 19],
       [ 2, 10, 18],
       [ 1,  9, 17],
       [ 0,  8, 16]])

In [115]:
np.rot90(my_3_8_array, k=-1)

array([[16,  8,  0],
       [17,  9,  1],
       [18, 10,  2],
       [19, 11,  3],
       [20, 12,  4],
       [21, 13,  5],
       [22, 14,  6],
       [23, 15,  7]])

## 7. Transpose like operations

- transpose
- swapaxes
- rollaxes

In [116]:
my_start_array = np.array(np.arange(24))
my_3_8_array = my_start_array.reshape((3,8))
my_2_3_4_array = my_3_8_array.reshape((2,3,4))

### transpose
for more information, please see: http://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html

###### 1-Dimension, no change

In [117]:
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [118]:
np.transpose(my_start_array)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

##### 2-Dimensions, 
exchange rows and columns (`a[i,j] becomes a[j,i]`)

In [119]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [120]:
np.transpose(my_3_8_array)

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

##### 3-Dimensions or more,
use 'axes' parameter

In [121]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [122]:
np.transpose(my_2_3_4_array, axes=(0,2,1))

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [123]:
np.transpose(my_2_3_4_array, axes=(2,1,0))

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

### swapaxes
from: http://docs.scipy.org/doc/numpy/reference/generated/numpy.swapaxes.html#numpy.swapaxes

##### returns
For Numpy >= 1.10, if a is an ndarray, then a view of a is returned; otherwise a new array is created. For earlier Numpy versions a view of a is returned only if the order of the axes is changed, otherwise the input array is returned.

In [124]:
np.swapaxes(my_2_3_4_array, 1, 0)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [125]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [126]:
np.swapaxes(my_2_3_4_array, 1, 0).shape

(3, 2, 4)

In [127]:
np.swapaxes(my_2_3_4_array, 2, 1)

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [128]:
np.swapaxes(my_2_3_4_array, 2, 0)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

### rollaxis
from: http://docs.scipy.org/doc/numpy/reference/generated/numpy.rollaxis.html#numpy.rollaxis

Roll the specified axis backwards, until it lies in a given position.

For Numpy >= 1.10 a view of a is always returned. For earlier Numpy versions a view of a is returned only if the order of the axes is changed, otherwise the input array is returned.

In [129]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [130]:
np.rollaxis(my_2_3_4_array, 0, 2)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [131]:
np.rollaxis(my_2_3_4_array, 0, 2).shape

(3, 2, 4)

##### Summary; from: http://stackoverflow.com/questions/15483156/generalizing-matrix-transpose-in-numpy

- Use np.transpose to permute all the axes at once. (Thanks to @jorgeca for pointing this out.)
- Use np.swapaxes to swap any two axes.
- Use np.rollaxis to "rotate" the axes.

## 8. Tiling arrays

#### tile
from: http://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html#numpy.tile

Construct an array by repeating A the number of times given by reps.

If reps has length d, the result will have dimension of max(d, A.ndim).

If A.ndim < d, A is promoted to be d-dimensional by prepending new axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication, or shape (1, 1, 3) for 3-D replication. If this is not the desired behavior, promote A to d-dimensions manually before calling this function.

If A.ndim > d, reps is promoted to A.ndim by pre-pending 1’s to it. Thus for an A of shape (2, 3, 4, 5), a reps of (2, 2) is treated as (1, 1, 2, 2).

In [132]:
my_start_array = np.array(np.arange(12))
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [133]:
np.tile(my_start_array, 3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11])

In [134]:
np.tile(my_start_array, 3).reshape((3,12))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [140]:
my_second_array = np.array(np.arange(7))
type(my_second_array)

numpy.ndarray

In [141]:
tile_1 = np.tile(my_second_array, (3, 1))
tile_1

array([[0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6]])

In [143]:
tile_2 = np.tile(tile_1, (2,2))
tile_2

array([[0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6]])

In [144]:
tile_3 = np.tile(tile_2, (3,1))
tile_3

array([[0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6]])

#### repeat()
In contrat with tile ( replicates entire arrays), __repeat()__ replicates elements within arrays to create new arrays

In [146]:
my_second_array

array([0, 1, 2, 3, 4, 5, 6])

In [147]:
np.repeat(my_second_array, 3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [148]:
my_repeatable_array = np.arange(24).reshape(2,3,4)
my_repeatable_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [149]:
np.repeat(my_repeatable_array, 2, axis=0)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [150]:
np.repeat(my_repeatable_array, 2, axis=1)

array([[[ 0,  1,  2,  3],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [20, 21, 22, 23]]])

In [151]:
np.repeat(my_repeatable_array, 2, axis=2)

array([[[ 0,  0,  1,  1,  2,  2,  3,  3],
        [ 4,  4,  5,  5,  6,  6,  7,  7],
        [ 8,  8,  9,  9, 10, 10, 11, 11]],

       [[12, 12, 13, 13, 14, 14, 15, 15],
        [16, 16, 17, 17, 18, 18, 19, 19],
        [20, 20, 21, 21, 22, 22, 23, 23]]])