In [2]:
import numpy as np

In [2]:
mya = np.arange(35)

In [4]:
mya

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [5]:
mya.shape = (7, 5)

In [6]:
mya

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [4]:
my_vector = np.array([-17, -4, 0, 2, 21, 37, 105])
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [6]:
zero_mod_7_mask = 0 == (my_vector % 7)
zero_mod_7_mask

array([False, False,  True, False,  True, False,  True])

In [7]:
sub_array = my_vector[zero_mod_7_mask]
sub_array

array([  0,  21, 105])

In [8]:
sub_array[sub_array > 0]

array([ 21, 105])

In [9]:
sub_array

array([  0,  21, 105])

### NumPy logical operators

In [10]:
mod_test = 0 == (my_vector % 7)

In [11]:
positive_test = my_vector > 0

In [12]:
combined_mask = np.logical_and(mod_test, positive_test)
combined_mask

array([False, False, False, False,  True, False,  True])

In [13]:
my_vector[combined_mask]

array([ 21, 105])

# Broadcasting

In [16]:
my_3d_array = np.arange(70)
my_3d_array.shape = (2, 7, 5)
my_3d_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [18]:
my_3d_array.shape

(2, 7, 5)

In [19]:
my_3d_array.ndim

3

In [20]:
my_3d_array.size

70

In [21]:
my_3d_array.dtype

dtype('int32')

In [22]:
left_mat = np.arange(6).reshape((2, 3))
right_mat = np.arange(15).reshape((3, 5))

### Operations along the axes

In [23]:
my_3d_array.sum()

2415

In [24]:
my_3d_array.sum(axis=0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [25]:
my_3d_array.sum(axis=1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [26]:
my_3d_array.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

### Broadcasting Rules

In [27]:
my_2d_array = np.ones(35, dtype='int_').reshape((7, 5)) * 3
my_2d_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [29]:
my_rand_2d_array = np.random.random((7, 5))
my_rand_2d_array

array([[0.48694612, 0.8334985 , 0.15273706, 0.87230421, 0.13893582],
       [0.72878086, 0.07571433, 0.61945256, 0.1655195 , 0.82005391],
       [0.55271816, 0.65075542, 0.13184734, 0.63720309, 0.92209207],
       [0.96195181, 0.40184743, 0.4096757 , 0.67335745, 0.5035414 ],
       [0.03834568, 0.16531766, 0.9727313 , 0.98192773, 0.12257843],
       [0.89126867, 0.13155398, 0.50854652, 0.29401863, 0.67152914],
       [0.55590258, 0.48808672, 0.60553509, 0.20610876, 0.4067652 ]])

In [30]:
# set precision for floating point variables to 4 
# decimal points:
np.set_printoptions(precision=4)
my_3d_array * my_rand_2d_array

array([[[ 0.    ,  0.8335,  0.3055,  2.6169,  0.5557],
        [ 3.6439,  0.4543,  4.3362,  1.3242,  7.3805],
        [ 5.5272,  7.1583,  1.5822,  8.2836, 12.9093],
        [14.4293,  6.4296,  6.9645, 12.1204,  9.5673],
        [ 0.7669,  3.4717, 21.4001, 22.5843,  2.9419],
        [22.2817,  3.4204, 13.7308,  8.2325, 19.4743],
        [16.6771, 15.1307, 19.3771,  6.8016, 13.83  ]],

       [[17.0431, 30.0059,  5.6513, 33.1476,  5.4185],
        [29.1512,  3.1043, 26.017 ,  7.1173, 36.0824],
        [24.8723, 29.9347,  6.1968, 30.5857, 45.1825],
        [48.0976, 20.4942, 21.3031, 35.6879, 27.1912],
        [ 2.109 ,  9.2578, 55.4457, 56.9518,  7.2321],
        [53.4761,  8.0248, 31.5299, 18.5232, 42.9779],
        [36.1337, 32.2137, 40.5709, 14.0154, 28.0668]]])

In [31]:
my_v = np.arange(5) * 7
my_v[0] = -1
my_v

array([-1,  7, 14, 21, 28])

In [32]:
my_3d_array / my_v

array([[[ -0.    ,   0.1429,   0.1429,   0.1429,   0.1429],
        [ -5.    ,   0.8571,   0.5   ,   0.381 ,   0.3214],
        [-10.    ,   1.5714,   0.8571,   0.619 ,   0.5   ],
        [-15.    ,   2.2857,   1.2143,   0.8571,   0.6786],
        [-20.    ,   3.    ,   1.5714,   1.0952,   0.8571],
        [-25.    ,   3.7143,   1.9286,   1.3333,   1.0357],
        [-30.    ,   4.4286,   2.2857,   1.5714,   1.2143]],

       [[-35.    ,   5.1429,   2.6429,   1.8095,   1.3929],
        [-40.    ,   5.8571,   3.    ,   2.0476,   1.5714],
        [-45.    ,   6.5714,   3.3571,   2.2857,   1.75  ],
        [-50.    ,   7.2857,   3.7143,   2.5238,   1.9286],
        [-55.    ,   8.    ,   4.0714,   2.7619,   2.1071],
        [-60.    ,   8.7143,   4.4286,   3.    ,   2.2857],
        [-65.    ,   9.4286,   4.7857,   3.2381,   2.4643]]])

In [33]:
my_3d_array % my_v

array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  4, 12, 13, 14],
        [ 0,  2,  3, 18, 19],
        [ 0,  0,  8,  2, 24],
        [ 0,  5, 13,  7,  1],
        [ 0,  3,  4, 12,  6]],

       [[ 0,  1,  9, 17, 11],
        [ 0,  6,  0,  1, 16],
        [ 0,  4,  5,  6, 21],
        [ 0,  2, 10, 11, 26],
        [ 0,  0,  1, 16,  3],
        [ 0,  5,  6,  0,  8],
        [ 0,  3, 11,  5, 13]]], dtype=int32)

In [34]:
# data definition for a structured array:
person_data_ref = [('name', 'S6'), ('height', 'f8'), 
                   ('weight', 'f8'), ('age', 'i8')]
person_data_ref

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [36]:
people_array = np.zeros((4), dtype=person_data_ref)
people_array

array([(b'', 0., 0., 0), (b'', 0., 0., 0), (b'', 0., 0., 0),
       (b'', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [37]:
people_array[3] = ('Delta', 73, 205, 34)
people_array[1] = ('Beta', 65, 112, 23)

In [38]:
people_array

array([(b'',  0.,   0.,  0), (b'Beta', 65., 112., 23),
       (b'',  0.,   0.,  0), (b'Delta', 73., 205., 34)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [39]:
ages = people_array['age']
ages

array([ 0, 23,  0, 34], dtype=int64)

In [40]:
pp = np.array([('Delta', 73, 205, 34), ('Beta', 65, 112, 23)], dtype=person_data_ref)

In [41]:
pp

array([(b'Delta', 73., 205., 34), (b'Beta', 65., 112., 23)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

# Plotting

In [100]:
import numpy as np
import matplotlib.pyplot as plt

mu, sigma = 100, 15
data_set = mu + sigma * np.random.randn(10000)

# the histogram of the data:
n, bins, patches = plt.hist(data_set, 50, density=True, facecolor='g', alpha=0.75)

plt.xlabel('Smarts')
plt.ylabel('Probability')
plt.title('Histogram of IQ')
plt.text(60, .025, r'$\mu=100,\ \sigma=15$')
plt.axis([40, 160, 0, 0.03])
plt.grid(True)
plt.show()

In [101]:
%matplotlib qtb
my_fi_fig = plt.figure('My first figure')

In [102]:
sub_plt_1 = my_fi_fig.add_subplot(2, 3, 1)
sub_plt_6 = my_fi_fig.add_subplot(2, 3, 6)

In [103]:
plt.plot(np.random.rand(50).cumsum(), 'k-')
my_fi_fig.show()

In [104]:
sub_plt_2 = my_fi_fig.add_subplot(2, 3, 2)
plt.plot(np.random.rand(50), 'go')

In [105]:
data_set_size = 15
low_mu, low_sigma = 50, 4.3
low_data_set = low_mu + low_sigma * np.random.randn(data_set_size)
high_mu, high_sigma = 57, 5.2
high_data_set = high_mu + high_sigma * np.random.randn(data_set_size)

days = list(range(1, data_set_size + 1))

In [107]:
plt.plot(days, low_data_set)

In [110]:
plt.plot(days, low_data_set,         
         days, high_data_set)
plt.show()

In [112]:
plt.plot(days, low_data_set,
         days, low_data_set, "vm",
         days, high_data_set, 
         days, high_data_set, "^k")
plt.show()

In [114]:
plt.plot( 
         days, high_data_set, "^k")
plt.show()

In [115]:
plt.plot(days, low_data_set,
         days, low_data_set, "vm",
         days, high_data_set, 
         days, high_data_set, "^k")
plt.xlabel('Day')
plt.ylabel('Temperature: degrees Farenheit')
plt.title('Randomized temperature data')
plt.show()

In [116]:
plt.plot(days, low_data_set,
         
         days, high_data_set
         )
plt.xlabel('Day')
plt.ylabel('Temperature: degrees Farenheit')
plt.title('Randomized temperature data')
plt.show()

In [117]:
plt.plot(
         days, high_data_set, "^k")
plt.xlabel('Day')
plt.ylabel('Temperature: degrees Farenheit')
plt.title('Randomized temperature data')
plt.show()

In [118]:
t1 = np.arange(0.0, 2.0, 0.1)
t2 = np.arange(0.0, 2.0, 0.01)

# note that plot returns a list of lines.  The "l1, = plot" usage
# extracts the first element of the list into l1 using tuple
# unpacking.  So l1 is a Line2D instance, not a sequence of lines
l1, = plt.plot(t2, np.exp(-t2))
l2, l3 = plt.plot(t2, np.sin(2 * np.pi * t2), '--go', t1, np.log(1 + t1), '.')
l4, = plt.plot(t2, np.exp(-t2) * np.sin(2 * np.pi * t2), 'rs-.')

plt.legend((l2, l4), ('oscillatory', 'damped'), loc='upper right', shadow=True)
plt.xlabel('time')
plt.ylabel('volts')
plt.title('Damped oscillation')
plt.show()