In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [3]:
my_list = [-17, 0, 4, 5, 9]
my_array = np.array(my_list)
my_array

array([-17,   0,   4,   5,   9])

In [4]:
my_array * 10

array([-170,    0,   40,   50,   90])

In [6]:
my_tuple = (14, -3.54, 5+7j)
np.array(my_tuple)

array([14.  +0.j, -3.54+0.j,  5.  +7.j])

### Difference between Python and NumPy data structures

In [7]:
my_list * 3

[-17, 0, 4, 5, 9, -17, 0, 4, 5, 9, -17, 0, 4, 5, 9]

In [8]:
my_array * 3

array([-51,   0,  12,  15,  27])