In [1]:
import numpy as np

In [2]:
ar = np.random.randint(1, 100, size=(6, 8))
ar

array([[23,  5, 21, 76, 73, 13, 26, 61],
       [ 3, 24, 84, 59, 82,  5, 10, 44],
       [59, 19, 31, 25, 59, 22, 85,  4],
       [12, 71, 52, 54, 48, 99, 80, 23],
       [92,  6, 24,  7, 75, 88, 61, 26],
       [ 1, 29, 62, 91, 30, 21, 31, 60]])

## Array Attributes:

In [3]:
ar.ndim

2

In [4]:
ar.shape

(6, 8)

In [5]:
ar.size

48

In [6]:
ar.dtype

dtype('int32')

In [7]:
# the size of bytes of each element in the array
ar.itemsize

4

In [8]:
ar.data

In [9]:
type(ar)

numpy.ndarray

## Array Creation:

#### 1. From a python list / tuple:

In [10]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

#### 2. seqeunces of sequences to nD arrays:

In [11]:
a2d = np.array([(1, 2, 3), (4, 5, 6)])
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
                [[11, 12, 13], [14, 15, 16], [17, 18, 19]]])
a3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

#### 3. Unknown elements / known size:

In [13]:
b = np.zeros((3, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
c = np.ones((3, 4), dtype=np.int8)
c

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [15]:
d = np.empty((6, 3))
d

array([[1.13766012e-311, 4.84184333e-322, 0.00000000e+000],
       [0.00000000e+000, 6.23058028e-307, 1.15998412e-028],
       [2.44171989e+232, 8.00801729e+159, 6.19319847e-071],
       [5.46814361e-095, 6.01347002e-154, 1.05190656e-153],
       [4.56295599e-144, 2.86530729e+161, 8.93176633e+271],
       [4.98131536e+151, 1.47916532e-071, 8.34451504e-308]])

In [16]:
d.dtype

dtype('float64')

#### 4. Sequences of numbers - arange / linspace:

######          arange:

In [17]:
e = np.arange(10, 30, 5)
e

array([10, 15, 20, 25])

###### linspace:

In [18]:
f = np.linspace(0, 2, 9)
f

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

See also: __array, zeros, zeros_like, ones, ones_like, empty, empty_like, arange, linspace, fromfunction, fromfile, numpy.random.Generator.rand, numpy.random.Generator.randn__

## Printing Arrays:

In [19]:
# prints just corners
g = np.arange(2500).reshape(50, 50)
g

array([[   0,    1,    2, ...,   47,   48,   49],
       [  50,   51,   52, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  147,  148,  149],
       ...,
       [2350, 2351, 2352, ..., 2397, 2398, 2399],
       [2400, 2401, 2402, ..., 2447, 2448, 2449],
       [2450, 2451, 2452, ..., 2497, 2498, 2499]])

In [20]:
# prints all:
import sys
np.set_printoptions(threshold=sys.maxsize)
g

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
          11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
          22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
          33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
          44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
          61,   62,   63,   64,   65,   66,   67,   68,   69,   70,   71,
          72,   73,   74,   75,   76,   77,   78,   79,   80,   81,   82,
          83,   84,   85,   86,   87,   88,   89,   90,   91,   92,   93,
          94,   95,   96,   97,   98,   99],
       [ 100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
         111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
         122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
         133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
         144,  145,  1

## Basic Operations:

##### arithmetic operations - element wise:

In [21]:
h = np.array([20, 30, 40, 50])
i = np.arange(4)
print('h array:\n', h)
print('\ni array:\n', i)

h array:
 [20 30 40 50]

i array:
 [0 1 2 3]


In [22]:
h-i

array([20, 29, 38, 47])

In [23]:
i**2

array([0, 1, 4, 9], dtype=int32)

In [24]:
10*np.sin(h)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [25]:
h<35

array([ True,  True, False, False])

##### * operates element wise:

In [26]:
j = np.array([[1, 1], [0, 1]])
k = np.array([[2, 0], [3, 4]])
print('j array:\n', j)
print('\nk array:\n', k)

j array:
 [[1 1]
 [0 1]]

k array:
 [[2 0]
 [3 4]]


In [27]:
j*k

array([[2, 0],
       [0, 4]])

In [28]:
# matrix product:
j@k

array([[5, 4],
       [3, 4]])

In [29]:
# matris product:
j.dot(k)

array([[5, 4],
       [3, 4]])

In [30]:
rg = np.random.default_rng(1) # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [31]:
b = rg.random((2, 3))
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [32]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [33]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [34]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

##### Many operations (sum, min, max, ...) implemented as methods of ndarray class:

In [35]:
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [36]:
b.sum()

21.29025228186613

In [37]:
b.min()

3.144159612719634

In [38]:
b.max()

3.950463696325935

In [39]:
l = np.arange(12).reshape(3, 4)
l

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
l.sum(axis=0)

array([12, 15, 18, 21])

In [41]:
l.min(axis=1)

array([0, 4, 8])

In [42]:
l.cumsum(axis=1) # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

## Universal functions:

In [43]:
m = np.arange(10)
m

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.exp(m)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [45]:
np.sqrt(m)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

## Indexing, Slicing, Iterating

###### One-Dimensional

In [46]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [47]:
a[2]

8

In [48]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [49]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [50]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [51]:
for i in a:
    print(i**(1/3))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


###### Multidimeansional - one index per array

In [52]:
def f(x, y):
    return 5 * x + y

In [53]:
a = np.fromfunction(f, (5, 4), dtype=int)
a

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

In [54]:
a[2, 3]

13

In [55]:
a[0:5, 1]

array([ 1,  6, 11, 16, 21])

In [56]:
a[-1]

array([20, 21, 22, 23])

## Shape Manipulation:

In [57]:
a

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

In [58]:
a = np.floor(10*rg.random((3, 4)))
a

array([[8., 4., 5., 0.],
       [7., 5., 3., 7.],
       [3., 4., 1., 4.]])

In [59]:
a.shape

(3, 4)

###### Folowing commands return a modified array / do not change the original:

In [60]:
a.ravel() # flatten array

array([8., 4., 5., 0., 7., 5., 3., 7., 3., 4., 1., 4.])

In [61]:
a.reshape(6, 2) 

array([[8., 4.],
       [5., 0.],
       [7., 5.],
       [3., 7.],
       [3., 4.],
       [1., 4.]])

In [62]:
a.T # returns the array, transposed

array([[8., 7., 3.],
       [4., 5., 4.],
       [5., 3., 1.],
       [0., 7., 4.]])

In [63]:
a

array([[8., 4., 5., 0.],
       [7., 5., 3., 7.],
       [3., 4., 1., 4.]])

###### resize() modifies the original array:

In [64]:
a.resize((2, 6))
a

array([[8., 4., 5., 0., 7., 5.],
       [3., 7., 3., 4., 1., 4.]])

In [65]:
a.reshape((3, -1))

array([[8., 4., 5., 0.],
       [7., 5., 3., 7.],
       [3., 4., 1., 4.]])

## Stacking together different arrays

In [66]:
a = np.floor(10*rg.random((2,2)))
b = np.floor(10*rg.random((2,2)))

In [67]:
a

array([[2., 2.],
       [7., 2.]])

In [68]:
b

array([[4., 9.],
       [9., 7.]])

In [69]:
np.vstack((a, b))

array([[2., 2.],
       [7., 2.],
       [4., 9.],
       [9., 7.]])

In [70]:
np.hstack((a, b))

array([[2., 2., 4., 9.],
       [7., 2., 9., 7.]])

In [71]:
np.column_stack((a, b)) # stacks 1D arrays as columns into a 2D array

array([[2., 2., 4., 9.],
       [7., 2., 9., 7.]])

In [72]:
a = np.array([4.,2.])
b = np.array([3.,8.])

In [73]:
a

array([4., 2.])

In [74]:
b

array([3., 8.])

In [75]:
np.column_stack((a, b)) # stacks 1D arrays as columns into a 2D array

array([[4., 3.],
       [2., 8.]])

In [76]:
np.hstack((a, b))

array([4., 2., 3., 8.])

In [77]:
np.vstack((a, b))

array([[4., 2.],
       [3., 8.]])

###### row_stack is equivalent to vstack for any input arrays. In fact, row_stack is an alias for vstack

> hstack stacks along their second axes,  

> vstack stacks along their first axes, and 

> concatenate allows for an optional arguments giving the number of the axis along which the concatenation should happen.

## Splitting one array into several smaller ones

In [78]:
a = np.floor(10*rg.random((2,12)))
a

array([[5., 2., 1., 9., 5., 1., 6., 7., 6., 9., 0., 5.],
       [4., 0., 6., 8., 5., 2., 8., 5., 5., 7., 1., 8.]])

In [79]:
# specifying the number of equally shaped arrays to return:
np.hsplit(a,3) # split into 3

[array([[5., 2., 1., 9.],
        [4., 0., 6., 8.]]),
 array([[5., 1., 6., 7.],
        [5., 2., 8., 5.]]),
 array([[6., 9., 0., 5.],
        [5., 7., 1., 8.]])]

In [80]:
# specifying the columns after which the division should occur:
np.hsplit(a,(3,4)) # Split a after the third and the fourth column

[array([[5., 2., 1.],
        [4., 0., 6.]]),
 array([[9.],
        [8.]]),
 array([[5., 1., 6., 7., 6., 9., 0., 5.],
        [5., 2., 8., 5., 5., 7., 1., 8.]])]

__vsplit__ splits along the vertical axis, and **array_split** allows one to specify along which axis to split

## Copies and Views

## Broadcasting

- how numpy treats arrays with different shapes during arithmetic operations
- the smaller array is “broadcast” across the larger array so that they have compatible shapes
- When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions and works its way forward. Two dimensions are compatible when:
 1. they are equal, or
 2. one of them is 1
 
__The Broadcasting Rule:__
In order to broadcast, the size of the trailing axes for both arrays in an operation must either be the same size or one of them must be one.

In [81]:
my_3d_arr = np.arange(70).reshape((2, 7, 5))
my_3d_arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [82]:
my_3d_arr * 10

array([[[  0,  10,  20,  30,  40],
        [ 50,  60,  70,  80,  90],
        [100, 110, 120, 130, 140],
        [150, 160, 170, 180, 190],
        [200, 210, 220, 230, 240],
        [250, 260, 270, 280, 290],
        [300, 310, 320, 330, 340]],

       [[350, 360, 370, 380, 390],
        [400, 410, 420, 430, 440],
        [450, 460, 470, 480, 490],
        [500, 510, 520, 530, 540],
        [550, 560, 570, 580, 590],
        [600, 610, 620, 630, 640],
        [650, 660, 670, 680, 690]]])

In [83]:
left_ar = np.arange(6).reshape((2, 3))
right_ar = np.arange(15).reshape((3, -1))

In [84]:
left_ar

array([[0, 1, 2],
       [3, 4, 5]])

In [85]:
right_ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
left_ar * right_ar

ValueError: operands could not be broadcast together with shapes (2,3) (3,5) 

In [87]:
np.inner(left_ar, right_ar)

ValueError: shapes (2,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [88]:
np.dot(left_ar, right_ar)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

## Advanced indexing and index tricks

#### Indexing with arrays of Integers

In [89]:
a = np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [90]:
i = np.array([1, 1, 3, 8, 5, 5])

In [91]:
a[i]

array([ 1,  1,  9, 64, 25, 25], dtype=int32)

###### Multidimensional arrays:

When the indexed array __a__ is multidimensional, a single array of indices refers to the first dimension of **a**

**Ex 1**: converting an image of labels into a color image using a palette:

In [92]:
palette = np.array([[0, 0, 0],        # black
                   [255, 0, 0],       # red
                   [0, 255, 0],       # green
                   [0, 0, 255],       # blue
                   [255, 255, 255]])  # white
image = np.array([[0, 1, 2, 3],       # each value corresponds to a color in the palette
                 [0, 3, 4, 0]])
palette[image]                        # the (2, 4, 3) color image

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0, 255]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

The array of indices for each dimmension must hace same shape

In [93]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
i = np.array([[0, 1],   # indices for the first dim of a
             [1, 2]])   

j = np.array([[2, 1],   # indices for the second dimension of a
             [3, 3]])

In [95]:
a[i, j]

array([[ 2,  5],
       [ 7, 11]])

In [96]:
a[i]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [97]:
a[i, 2]

array([[ 2,  6],
       [ 6, 10]])

In [98]:
a[:, j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [99]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**Ex 2**: search of the maximum value of time-dependent series:

In [100]:
time = np.linspace(20, 145, 5)     # time scale
data = np.sin(np.arange(20)).reshape(5, 4)

In [101]:
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [102]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [103]:
# index of maxima for each series:
ind = data.argmax(axis=0)
ind

array([2, 0, 3, 1], dtype=int64)

In [104]:
# time corresponding to the maxima:
time_max = time[ind]
time_max

array([ 82.5 ,  20.  , 113.75,  51.25])

In [105]:
data_max = data[ind, range(data.shape[1])]  # => data[ind[0],0], data[ind[1], 1] ...
data_max

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [106]:
np.all(data_max == data.max(axis=0))

True

###### Indexing with arrays as a target to assign to:

In [109]:
a = np.arange(7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [110]:
a[[1, 3, 4]] = 0
a

array([0, 0, 2, 0, 0, 5, 6])

###### ! when the list of indices contains repetitions, the assignment is done several times, leaving behind the last value

In [111]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [112]:
a[[0, 0, 2]] = [1, 2, 3]
a

array([2, 1, 3, 3, 4])

###### Indexing with Boolean Arrays

In [114]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
b = a > 4       # b = boolean with a's shape
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [116]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [117]:
a[b] = 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

###### Second way of indexing with booleans: similar to integer indexing; for each dimension of the array we give a 1D boolean array selecting the slices we want:

In [119]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
b1 = np.array([False, True, True])
b2 = np.array([True, False, True, False])

In [121]:
a[b1, :]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
a[b1]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
a[:, b2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [124]:
a[b1, b2]

array([ 4, 10])

###### The ix_() function:

Used to combine different vectors so as to obtain the result for each n-uplet. For example, if you want to compute all the a+b*c for all the triplets taken from each of the vectors a, b and c:

In [125]:
a = np.array([2, 3, 4, 5])
b = np.array([8, 5, 4])
c = np.array([5, 4, 6, 8, 3])

ax, bx, cx = np.ix_(a, b, c)

In [126]:
ax

array([[[2]],

       [[3]],

       [[4]],

       [[5]]])

In [127]:
bx

array([[[8],
        [5],
        [4]]])

In [128]:
cx

array([[[5, 4, 6, 8, 3]]])

In [129]:
ax.shape, bx.shape, cx.shape

((4, 1, 1), (1, 3, 1), (1, 1, 5))

In [130]:
result = ax + bx * cx
result

array([[[42, 34, 50, 66, 26],
        [27, 22, 32, 42, 17],
        [22, 18, 26, 34, 14]],

       [[43, 35, 51, 67, 27],
        [28, 23, 33, 43, 18],
        [23, 19, 27, 35, 15]],

       [[44, 36, 52, 68, 28],
        [29, 24, 34, 44, 19],
        [24, 20, 28, 36, 16]],

       [[45, 37, 53, 69, 29],
        [30, 25, 35, 45, 20],
        [25, 21, 29, 37, 17]]])