In [1]:
import numpy as np

In [5]:
ar = np.random.randint(1, 100, size=(6, 8))
ar

array([[66, 58,  2,  3, 76, 51, 78, 86],
       [34, 91, 97, 88, 19, 31, 23, 30],
       [74, 77, 78, 90, 60, 30, 46, 76],
       [88, 10, 19, 94,  9, 10, 67, 91],
       [37, 44, 22, 64, 76, 89, 18, 14],
       [70, 32, 52, 62, 94, 98, 68, 64]])

In [7]:
ar.ndim

2

In [8]:
ar.shape

(6, 8)

In [9]:
ar.size

48

In [10]:
# size of bytes of each element in array
ar.itemsize

4

In [11]:
ar.data

In [12]:
type(ar)

numpy.ndarray

### Array creation

##### 1. From list / tuple

In [13]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

##### 2. nD arrays:

In [15]:
a2d = np.array([[1, 2, 3], [4, 5, 6]])
a2d

array([[1, 2, 3],
       [4, 5, 6]])

##### 3. unknown elements - known size

In [16]:
b = np.zeros((3, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
c = np.ones((3, 4), dtype=np.int16)
c

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [18]:
d = np.empty((6, 3))
d

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306],
       [1.69120688e-306, 6.23058028e-307, 8.45593934e-307],
       [7.56593017e-307, 1.11261027e-306, 1.11261502e-306],
       [1.42410839e-306, 7.56597770e-307, 6.23059726e-307],
       [1.42419530e-306, 1.37962185e-306, 1.37962049e-306],
       [1.24610723e-306, 1.60219035e-306, 9.34609790e-307]])

In [19]:
d.dtype

dtype('float64')

##### 4. sequences: arange / linespace

In [21]:
e = np.arange(11, 30, 5)
e

array([11, 16, 21, 26])

In [23]:
f = np.linspace(0, 2, 9)
f

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [31]:
arr = np.arange(0, 300, dtype=np.int8)
arr

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
         55,   56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
         66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
         77,   78,   79,   80,   81,   82,   83,   84,   85,   86,   87,
         88,   89,   90,   91,   92,   93,   94,   95,   96,   97,   98,
         99,  100,  101,  102,  103,  104,  105,  106,  107,  108,  109,
        110,  111,  112,  113,  114,  115,  116,  117,  118,  119,  120,
        121,  122,  123,  124,  125,  126,  127, -128, -127, -126, -125,
       -124, -123, -122, -121, -120, -119, -118, -117, -116, -115, -114,
       -113, -112, -111, -110, -109, -108, -107, -1